[build]
publish = "public"
command = "npm run abridge -- '--base-url https://blog.hafi.is-a.dev'"

[build.environment]
ZOLA_VERSION = "0.19.1"

[context.deploy-preview]
command = "npm run abridge -- '--drafts --base-url https://blog.hafi.is-a.dev'"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "https://blog.hafi.is-a.dev"
Access-Control-Allow-Methods = "GET, POST, OPTIONS"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=63072000; includeSubdomains"
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy (disabled everything except autoplay, local-fonts, screen-wake-lock, speaker-selection)
# opt out of Federated Learning of Cohorts (aka "FLoC") - https://amifloced.org/
Permissions-Policy = "interest-cohort=(), accelerometer=(), ambient-light-sensor=(), battery=(), bluetooth=(), browsing-topics=(), camera=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(), gamepad=(), geolocation=(), gyroscope=(), hid=(), identity-credentials-get=(), idle-detection=(), magnetometer=(), microphone=(), midi=(), otp-credentials=(), payment=(), picture-in-picture=(), publickey-credentials-create=(), publickey-credentials-get=(), serial=(), storage-access=(), sync-xhr=(), usb=(), web-share=(), window-management=(), xr-spatial-tracking=()"
Content-Security-Policy = "default-src 'none'; frame-ancestors 'none'; object-src 'none'; base-uri 'self' hafis-code-continuum.netlify.app; manifest-src 'self' hafis-code-continuum.netlify.app; worker-src 'self' hafis-code-continuum.netlify.app; form-action 'self' hafis-code-continuum.netlify.app; connect-src 'self' hafis-code-continuum.netlify.app https://cdn.jsdelivr.net *.hyvor.com ws://*.hyvor.com; script-src 'self' hafis-code-continuum.netlify.app talk.hyvor.com; img-src 'self' data: hafis-code-continuum.netlify.app talk.hyvor.com cdn.cloudflare.com; frame-src 'self' hafis-code-continuum.netlify.app www.youtube-nocookie.com player.vimeo.com streamable.com www.streamable.com; media-src 'self' data: hafis-code-continuum.netlify.app cdn.cloudflare.com www.youtube-nocookie.com player.vimeo.com; font-src 'self' hafis-code-continuum.netlify.app cdn.cloudflare.com cdn.jsdelivr.net fonts.gstatic.com; style-src 'self' hafis-code-continuum.netlify.app talk.hyvor.com cdn.cloudflare.com cdn.jsdelivr.net fonts.googleapis.com 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=' 'sha256-p08VBe6m5i8+qtXWjnH/AN3klt1l4uoOLsjNn8BjdQo=' ;"
[[headers]]
for = "*.js" #javascript
[headers.values]
Cache-Control = "public, max-age=604800, must-revalidate"
[[headers]]
for = "*.css" #stylesheet
[headers.values]
Cache-Control = "public, max-age=604800, must-revalidate"
[[headers]]
for = "*.svg" #image/favicon
[headers.values]
Cache-Control = "public, max-age=604800"
[[headers]]
for = "*.png" #image/favicon
[headers.values]
Cache-Control = "public, max-age=604800"
[[headers]]
for = "*.ico" #image/favicon
[headers.values]
Cache-Control = "public, max-age=604800"
[[headers]]
for = "*.jpg" #image
[headers.values]
Cache-Control = "public, max-age=604800"
[[headers]]
for = "*.jpeg" #image
[headers.values]
Cache-Control = "public, max-age=604800"
[[headers]]
for = "*.gif" #image
[headers.values]
Cache-Control = "public, max-age=604800"
[[headers]]
for = "*.webp" #image
[headers.values]
Cache-Control = "public, max-age=604800"
[[headers]]
for = "*.avif" #image
[headers.values]
Cache-Control = "public, max-age=604800"
[[headers]]
for = "*.mp4" #video
[headers.values]
Cache-Control = "public, max-age=604800"
[[headers]]
for = "*.webm" #video
[headers.values]
Cache-Control = "public, max-age=604800"
[[headers]]
for = "*.mp3" #audio
[headers.values]
Cache-Control = "public, max-age=604800"
[[headers]]
for = "*.ogg" #audio
[headers.values]
Cache-Control = "public, max-age=604800"
[[headers]]
for = "*.otf" #font
[headers.values]
Cache-Control = "public, max-age=604800"
[[headers]]
for = "*.eot" #font
[headers.values]
Cache-Control = "public, max-age=604800"
[[headers]]
for = "*.ttf" #font
[headers.values]
Cache-Control = "public, max-age=604800"
[[headers]]
for = "*.woff" #font
[headers.values]
Cache-Control = "public, max-age=604800"
[[headers]]
for = "*.woff2" #font
[headers.values]
Cache-Control = "public, max-age=604800"
